apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "chmod 777 -R /opt/bitnami/pgbouncer/conf/"]
          volumeMounts:
            - name: options
              mountPath: /opt/bitnami/pgbouncer/conf/
      containers:
        - name: pgbouncer
          image: bitnami/pgbouncer
          ports:
            - containerPort: 6432
          env:
          - name: POSTGRESQL_DATABASE
            value: "*******"
          - name: POSTGRESQL_USERNAME
            value: "*******"
          - name: POSTGRESQL_PASSWORD
            value: "*******"
          - name: POSTGRESQL_HOST
            value: "10.110.246.108"
          - name: POSTGRESQL_PORT
            value: "5432"
          - name: PGBOUNCER_PORT
            value: "6432"
          - name: PGBOUNCER_MAX_CLIENT_CONN
            value: "500"
          - name: PGBOUNCER_DATABASE
            value: "*******"
          - name: PGBOUNCER_POOL_MODE
            value: transaction
          volumeMounts:
            - name: pgbouncer-config 
              mountPath: /bitnami/pgbouncer/conf/
              readOnly: true 
            - name: pgbouncer-config 
              mountPath: /etc/pgbouncer/
              readOnly: true 
            - name: pgbouncer-config
              mountPath: /opt/bitnami/pgbouncer/conf/
      volumes:
        - name: pgbouncer-config 
          configMap:
            name: pgbouncer-config
        - name: options
          persistentVolumeClaim:
            claimName: pgbouncer-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
data:
  userlist.txt: |
    "postgres" "kinthop1598524!#"
  pgbouncer.ini: |
    [databases]
    *=host=10.98.171.9 port=6061 dbname=kintshop user=postgres password=kinthop1598524!#
    *=host=10.108.33.216 port=6062 dbname=kintshop user=postgres password=kinthop1598524!#

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
    logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
    admin_users = postgres
    pool_mode = transaction
---
kind: Service
apiVersion: v1
metadata:
  name: pgbouncer
  labels:
    app: pgbouncer
spec:
  ports:
    - protocol: TCP
      port: 6432
      targetPort: 6432
  selector:
    app: pgbouncer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgbouncer-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: pgbouncer-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pgbouncer"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgbouncer-claim  # Sets name of PVC
  labels:
    app: pgbouncer-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 1Gi  # Sets volume size
  volumeName: pgbouncer-volume