apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-config
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    mysql_servers =
    (
        {
            address = "10.98.171.9",   
            port = 6061,
            hostgroup = 10,                      
            max_connections = 100
        },
        {
            address = "10.108.33.216", 
            port = 6062,
            hostgroup = 20,                      
            max_connections = 100
        }
    )

    mysql_users =
    (
        {
            username = "postgres",
            password = "kinthop1598524!#",
            default_hostgroup = 10,
            transaction_persistent = 0
        }
    )

    mysql_query_rules =
    (
        {
            rule_id = 1,
            active = 1,
            match_pattern = "^SELECT",
            destination_hostgroup = 20,
            apply = 1
        }
    )
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      containers:
      - name: proxysql
        image: percona/proxysql2:latest
        ports:
        - containerPort: 6033  
        - containerPort: 6032  
        volumeMounts:
        - name: proxysql-config
          mountPath: /etc/proxysql.cnf
          subPath: proxysql.cnf
      volumes:
      - name: proxysql-config
        configMap:
          name: proxysql-config